import Head from 'next/head'
import { Header, Footer } from '../sharedComponents';
import MainContent from '../sections/HomePage/MainContent';
 
export default function Home() {
  return (
    <div>
      <Head>
        <title>Cookie Stand Admin</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <Header />
      <MainContent />
      <Footer />
    </div>
  )
}
