import Head from 'next/head';

const HeadComp = () => (
  <Head>
    <title>Cookie Stand Admin</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/cookie.ico" />
  </Head>
)
export default HeadComp;
